import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import Navbar from "@/components/navbar";
import { Providers } from "@/app/providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Booking Rooms",
  description: "Generated by create next app",
};

export default function MainLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className=" min-h-screen">
       <div
        className={`
          ${geistSans.variable} 
          ${geistMono.variable} 
          antialiased
          max-w-[960px]
          mx-auto
          min-h-screen
          bg-[var(--background)]
          shadow-[0_0_30px_rgba(0,0,0,0.5)]
        `}
        >
        <Providers>
          <Navbar />
          {/* เพิ่ม padding-top เพื่อให้เนื้อหาไม่ถูกบัง และ padding-bottom สำหรับ mobile menu */}
          <main className="">
            {children}
          </main>
        </Providers>
      </div>
    </div>
  );
}